# Generated by Django 3.1.2 on 2022-05-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'サブリスト',
                'db_table': 'subarea',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100, verbose_name='工程')),
                ('construction_name', models.CharField(max_length=255, verbose_name='工事名称')),
                ('danger_list', models.CharField(choices=[('挟まれ', '挟まれ/Actuator'), ('重量物', '重量物/Block'), ('車両', '車両/Car'), ('転落', '転落/Drop'), ('感電', '感電/Electric Shock'), ('火災', '火災/Fire')], max_length=30, verbose_name='危険項目')),
                ('environmental_risk', models.CharField(blank=True, max_length=100, null=True, verbose_name='環境リスク')),
                ('work_content', models.CharField(max_length=255, verbose_name='作業内容')),
                ('work_company', models.CharField(max_length=100, verbose_name='作業部署/仕入先')),
                ('work_person', models.CharField(max_length=20, verbose_name='工事担当')),
                ('quality_check', models.CharField(blank=True, choices=[('溶接', '溶接'), ('面', '面'), ('仕様', '仕様'), ('錆', '錆'), ('板合せ', '精度'), ('組付', '組付'), ('打刻', '打刻'), ('その他', 'その他')], max_length=20, null=True, verbose_name='品質確認項目')),
                ('quality_check_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='品質確認担当')),
                ('safety_check', models.CharField(blank=True, choices=[('○', '○')], max_length=10, null=True, verbose_name='安全立会')),
                ('safety_check_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='安全立会担当')),
                ('work_start', models.DateTimeField(verbose_name='開始日時')),
                ('work_end', models.DateTimeField(verbose_name='終了日時')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='依頼事項/備考')),
                ('dummy', models.CharField(blank=True, choices=[('○', '○')], max_length=10, null=True, verbose_name='生産指示ダミー')),
                ('goguchi_change', models.CharField(blank=True, choices=[('○', '○')], max_length=10, null=True, verbose_name='号口変化点')),
                ('seijun_change', models.CharField(blank=True, choices=[('○', '○')], max_length=10, null=True, verbose_name='生準変化点')),
                ('status', models.CharField(blank=True, choices=[('工事前', '工事前'), ('進行中', '進行中'), ('完了', '完了')], max_length=10, null=True, verbose_name='進捗')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='計画者')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.subarea', verbose_name='サブエリア')),
            ],
            options={
                'verbose_name_plural': '工事リスト',
                'db_table': 'construction',
                'ordering': ('work_start',),
            },
        ),
    ]
